### ISSUE TITLE
Ошибка после добавления новой модели.

### ISSUE THREAD

**Issue by serjmors** [qtLex/SmallGame_Box#10]
После добавления модели персонажа, при запуске игры в лог постоянно валится сообщение:
"Invalid optimized game object"

Обрати внимание когда будешь переделывать аниматор.

**Comment by qtLex** [comment]
Вот нашел описание ошибки на issuetracker Unity:
http://issuetracker.unity3d.com/issues/invalid-optimized-game-object-errors-are-spammed-when-an-optimized-animated-object-is-set-as-a-child-of-any-other-object

Вроде наш случай.

Можно попробовать отключить оптимизацию рига. Или я не правильно понимаю причину возникновения ошибки?

**Comment by qtLex** [comment]
После последнего обновления еще появилась такая ошибка "refCount == 0" после запуска в режиме игры. появляется при клике мышью как в игровом режиме так и в сцене

**Comment by qtLex** [comment]
А все, это мой косяк с обновлением. А вторая ошибка это неправильно настроенный персонаж. Исправлено.
