### ISSUE TITLE
Переименование основной ветки.

### ISSUE THREAD

**Issue by serjmors** [qtLex/SmallGame_Box#11]
Работаем в ветке update to unity v5. Переименуй плз в "development" не могу понять как без консоли внешнюю ветку переименовать.

**Comment by qtLex** [comment]
С переименованием возникли проблемы, у меня на локале норм переименовывается, но на сервер все равно льется со старым именем. Я даже ветку удалять напрямую пробовал - не помогло. 

Потом на вики нашел такое:

Переименовать любой бранч:
git branch -m current_name new_name

Ситуация немного усложняется в случае если вы уже запушили ветку на удаленный сервер, переименовываем ее так:

git checkout -b <new-branch-name> создаем новую ветку
git push origin <new-branch-name> пушим ее на удаленный сервер
git push origin :<old-branch-name> удаляем старую ветку

Новую ветку я создал. Старую пока не удалял.
