### ISSUE TITLE
Перемещающиеся кубы

### ISSUE THREAD

**Issue by serjmors** [qtLex/SmallGame_Box#16]
Судя по коду кубы перемещаются просто анимацией.
Ключ куба в объекте Grid определяется его текущим положением в сетке. Получение кубов выполняется по текущим координатам. Соответственно, если перемещать куб и не менять его ключ в сетке, то найти его по новым координатам не возможно.

**Comment by qtLex** [comment]
Добавил обновление ключа в сетке. Обнаружил проблему с обновлением сетки в сингле(не обновлялась), тоже поправил. Вроде не должно помешать доработкам в ветке EditorMode, но до объединения гарантии нет. Возможно придется подкрутить.

**Comment by serjmors** [comment]
В ветке EditMode  для класса CubeGridBase реализован метод move, можно его юзать

**Comment by qtLex** [comment]
В своей ветке реализовывал новый метод. При объединении учту и оставлю один.

**Comment by qtLex** [comment]
Реализовано
