### ISSUE TITLE
Зависшие подписки на события(IvEd)

### ISSUE THREAD

**Issue by qtLex** [qtLex/SmallGame_Box#17]
После загрузки уровня или уничтожения куба выполнять описку от событий.

**Comment by serjmors** [comment]
События привязаны к объекту? Может в базовом классе каждого объекта на OnDestroy() или в деструкторе прописать явную отписку по this?

**Comment by qtLex** [comment]
Так и планировал. Думал сделать после объединения, поэтому и записал для себя, чтоб не забыть.

**Comment by qtLex** [comment]
Исправлено
