### ISSUE TITLE
прозрачность объектов

### ISSUE THREAD

**Issue by qtLex** [qtLex/SmallGame_Box#6]
Работет корректно только для неподвижного кубика. Так же раобраться с шейдерами для кубиков(текущий на новой версии не работает).В пятерке появились новые шейдеры, возможно лудше использовать их, пока что поставил старый с прозрачностью.

**Comment by serjmors** [comment]
Поправил шейдер для текущей версии. Попробуй откатить код прозрачность, всё должно заработать.

**Comment by qtLex** [comment]
Применил исправленый шейдер и востановил скрипт. Проблемы это не решило так как скрипт рабоает только если материал висит на корневом объекте. Посмотрю и подправлю.

**Comment by qtLex** [comment]
Исправлено
